version: '3'

services:
    database:
        build: 
            context: ./docker/mysql 
        environment:
            - MYSQL_DATABASE=db
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./src:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
            - php-fpm
        ports:
            - "80:80"
            - "443:443"
    php-fpm:
        build: 
            context: ./docker/php
        volumes:
            - ./src:/var/www